export const DAYS = [
  {
    id: "day-one",
    path: "/program/day-one",
    label: "DAY 1",
    name: "five maximum effort sets",
    number: 1,
    heading2: "5 MAXIMUM EFFORT SETS",
    heading3: "90s RECOVERY",
  },
  {
    id: "day-two",
    path: "/program/day-two",
    label: "DAY 2",
    name: "pyramid",
    number: 2,
    heading2: "PYRAMID",
    heading3: "10s RECOVERY / REP",
  },
  {
    id: "day-three",
    path: "/program/day-three",
    label: "DAY 3",
    name: "3 training sets with 3 grips",
    number: 3,
    heading2: "3 TRAINING SETS / 3 GRIPS",
    heading3: "60s RECOVERY",
  },
  {
    id: "day-four",
    path: "/program/day-four",
    label: "DAY 4",
    name: "max training sets",
    number: 4,
    heading2: "MAXIMUM (9+) TRAINING SETS",
    heading3: "60s RECOVERY",
  },
  {
    id: "day-five",
    path: "/program/day-five",
    label: "DAY 5",
    name: "repeat the most difficult day (1-4)",
    number: 5,
    heading2: "REPEAT THE MOST DIFFICULT DAY (1 - 4)",
    heading3: "CHOOSE A DAY BELOW",
  },
];
